const ERRORS = {
    EMAIL_EXISTS: "EMAIL EXISTS",
    NICKNAME_EXISTS: "NICKNAME EXISTS",
    WRONG_CREDENTIALS: "WRONG CREDENTIALS",
    PLANT_EXISTS: "PLANT EXISTS",
    UNAUTHORIZED: "UNAUTHORIZED"
}

module.exports = ERRORS;